import type { ExperienceItem } from '@/types/portfolio';

export const experienceSection = {
  title: 'Professional Experience',
  description: '[Placeholder: The narrative of transitioning from product design to platform architecture, powering multiple domains from a shared foundation.]',
  platformEvolutionHeading: 'Platform Evolution',
  platformEvolutionPlaceholder: '[Architecture Diagram Placeholder: MDPlix → Reusable Platform → Products]',
  productEngineeringHeading: 'Product Engineering',
  enterpriseConsultingHeading: 'Enterprise Consulting',
  internalEngineeringHeading: 'Internal Engineering',
};

export const experience: ExperienceItem[] = [
  {
    id: 'mdplix',
    title: '[Product Name Placeholder - MDPlix]',
    role: '[Role Placeholder]',
    dateRange: '[Date Placeholder]',
    category: 'Product Engineering',
    description: '[Description about the foundational architecture.]',
    technologies: ['[Tech 1]', '[Tech 2]'],
  },
  {
    id: 'urbanhouzz',
    title: '[Product Name Placeholder - UrbanHouzz]',
    role: '[Role Placeholder]',
    dateRange: '[Date Placeholder]',
    category: 'Product Engineering',
    description: '[Description about adapting the platform.]',
    technologies: ['[Tech 1]', '[Tech 2]'],
  },
  {
    id: 'azentikforce',
    title: '[Product Name Placeholder - AzentikForce]',
    role: '[Role Placeholder]',
    dateRange: '[Date Placeholder]',
    category: 'Product Engineering',
    description: '[Description about extending the platform.]',
    technologies: ['[Tech 1]', '[Tech 2]'],
  },
  {
    id: 'shoppyforce',
    title: '[Product Name Placeholder - Shoppyforce]',
    role: '[Role Placeholder]',
    dateRange: '[Date Placeholder]',
    category: 'Product Engineering',
    description: '[Description about new modules on shared foundation.]',
    technologies: ['[Tech 1]', '[Tech 2]'],
  },
  {
    id: 'pipeline-management',
    title: '[Client Project Placeholder - Pipeline Management]',
    role: '[Consulting Role Placeholder]',
    dateRange: '[Date Placeholder]',
    category: 'Enterprise Consulting',
    description: '[Description of enterprise work through Suflon Tech LLP and AMSYS.]',
    technologies: ['[Tech 1]', '[Tech 2]'],
  },
  {
    id: 'dc-google',
    title: '[Internal Tool Placeholder - DC Google Automation]',
    role: '[Role Placeholder]',
    dateRange: '[Date Placeholder]',
    category: 'Internal Engineering',
    description: '[Description of internal automation tool.]',
    technologies: ['[Tech 1]'],
  },
  {
    id: 'sql-script',
    title: '[Internal Tool Placeholder - SQL Executable Script]',
    role: '[Role Placeholder]',
    dateRange: '[Date Placeholder]',
    category: 'Internal Engineering',
    description: '[Description of productivity enhancement script.]',
    technologies: ['[Tech 1]'],
  },
  {
    id: 'woctor-api',
    title: '[Internal Tool Placeholder - Woctor Backend Automation API]',
    role: '[Role Placeholder]',
    dateRange: '[Date Placeholder]',
    category: 'Internal Engineering',
    description: '[Description of automation API.]',
    technologies: ['[Tech 1]'],
  },
];
